spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Madhura@58
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Config-Default
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
